rootProject.name = 'ecommerce'

include 'common-lib'
include 'category-service'
include 'product-service'
include 'order-service'
include 'user-service'
include 'notification-service'
include 'api-getway'
include 'discovery-server'
include 'auth-service'
include 'inventory-service'
include 'shipping-service'
include 'payment-service'
include 'cart-service'
include 'role-service'
include 'permission-service'
