server:
  #  servlet:
  #    context-path: /order-service
  port: 8010


#H2 DB
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_services_db
    username: postgres
    password: manhden123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    #    mức độ log mặc đinh
    root: INFO
    #    giảm log của spring
    org.springframework: WARN
    #    log tri tiết cho code
    com.example.productservice: debug
  #    định dạng log trên console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/inventory-service.log



  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/